name: gym_app
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  
  flutter:
    sdk: flutter
  
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  firebase_database: ^1.0.4
  firebase_core: ^0.2.5
  firebase_auth: ^0.5.2
  firebase_storage: ^1.0.4
  connectivity: ^0.3.2
  http: '>=0.11.3+12'
  shared_preferences: ^0.4.3
  autocomplete_textfield: ^1.4.1
  datetime_picker_formfield: ^0.1.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  assets: 
  - assets/1.jpg
  - assets/2.jpg
  - assets/3.jpg
  - assets/4.jpg
  - assets/5.jpg
  - assets/6.jpg
  - assets/7.jpg
  - assets/targets/quads.png
  - assets/targets/upperleg.png
  - assets/JSON/gymapp-e8453-export.json
  - assets/JSON/testingLocal.json
  - assets/personalized.jpeg
  - assets/journal.jpg
  - assets/jnal.jpeg
  - assets/journal1.jpeg
  - assets/Diary.png
  - assets/Network.png
  - assets/Evolve Logo White.png
  - assets/Evolve Logo.png
  - assets/notebook.png
  - assets/group.png


  fonts: 
    - family: Prompt
      fonts: 
        - asset: assets/fonts/Prompt-Regular.ttf

    - family: Montserrat
      fonts: 
        - asset: assets/fonts/Montserrat-Regular.ttf

    - family: Haymaker
      fonts: 
        - asset: assets/fonts/Haymaker.ttf


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
